apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointer
  template:
    metadata:
      labels:
        app: pointer
    spec:
      containers:
      - name: pointer
        image: vinex22/pointer:1.0
          
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: pointer-service
spec:
  type: NodePort
  selector:
    app: pointer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30300

